version: "3.3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/root/workspace
    env_file:
      - .env.test
    environment:
      - ENV=test
    tty: true
    command: /bin/bash
    shm_size: ${DOCKER_SHM_SIZE}
