version: "3.3"
services:
  project:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/root/workspace
    env_file:
      - .env
    tty: true # retain container up
    command: /bin/bash
    shm_size: ${DOCKER_SHM_SIZE}
