version: "3.3"
services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/root/workspace
      - /datadrive/hdd3/text-to-image:/datadrive
    env_file:
      - .env.dev
    environment:
      - ENV=dev
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    tty: true # retain container up
    command: /bin/bash
    shm_size: ${DOCKER_SHM_SIZE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
