# name: pytest

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]

# permissions:
#   contents: read

# jobs:
#   pytest:
#     if: github.event.pull_request.draft == false
#     runs-on: ubuntu-latest
#     environment:
#       name: development

#     steps:
#       - uses: actions/checkout@v3

#       - name: Install Docker Compose
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y docker-compose

#       - name: Make .env file
#         run: |
#           cp .env.example .env.test

#       - name: Build the containers & Start the containers
#         run: |
#           docker-compose -f docker-compose.test.yml --env-file .env.test up --build -d

#       - name: Test with pytest
#         run: |
#           docker exec text-to-image_test_1 pytest -v

#       - name: Clean up
#         if: always()
#         run: |
#           docker-compose -f docker-compose.test.yml --env-file .env.test down
